# Get all currencies

GET http://localhost:4444/.netlify/functions/currencies

###

POST http://localhost:4444/.netlify/functions/currencies

###

POST https://superb-sorbet-ca09c6.netlify.app/.netlify/functions/currencies