# Get all currencies

GET http://localhost:8888/api/currencies

###

POST http://localhost:8888/api/currencies

###

OPTIONS http://localhost:8888/api/currencies

###

GET https://davland7.netlify.app/.netlify/functions/currencies

###

GET https://davland7.netlify.app/api/currencies

###

POST https://davland7.netlify.app/.netlify/functions/currencies

###

OPTIONS https://davland7.netlify.app/.netlify/functions/currencies
