# Get all currencies

GET http://localhost:8888/.netlify/functions/currencies

###

POST http://localhost:8888/.netlify/functions/currencies

###

GET https://davland7.netlify.app/.netlify/functions/currencies

###

POST https://davland7.netlify.app/.netlify/functions/currencies
